# Generated by Django 5.2.15 on 2026-07-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstabelecimentoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(unique=True)),
            ],
            options={
                'verbose_name': 'Estabelecimento de Saúde',
                'verbose_name_plural': 'Estabelecimentos de Saúde',
                'db_table': 'estabelecimento_saude',
            },
        ),
    ]
