# Generated by Django 5.2.15 on 2026-09-28 01:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstabelecimentoSaude', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estabelecimentosaude',
            options={'ordering': ['nome'], 'verbose_name': 'Unidade de Saúde', 'verbose_name_plural': 'Unidades de Saúde'},
        ),
        migrations.AddField(
            model_name='estabelecimentosaude',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='estabelecimentosaude',
            name='competencias',
            field=models.TextField(blank=True, help_text='Contém horários específicos como coleta laboratorial e salas de vacina (aceita marcação HTML)', null=True, verbose_name='Competências / Informações Adicionais'),
        ),
        migrations.AddField(
            model_name='estabelecimentosaude',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estabelecimentosaude',
            name='email',
            field=models.CharField(blank=True, help_text='E-mail(s) de contato da unidade', max_length=255, null=True, verbose_name='E-mail(s)'),
        ),
        migrations.AddField(
            model_name='estabelecimentosaude',
            name='endereco',
            field=models.TextField(blank=True, help_text='Endereço completo, bairro e CEP', null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='estabelecimentosaude',
            name='gestor',
            field=models.CharField(blank=True, help_text='Nome do gestor responsável', max_length=150, null=True, verbose_name='Gestor(a)'),
        ),
        migrations.AddField(
            model_name='estabelecimentosaude',
            name='horario',
            field=models.CharField(blank=True, help_text='Horário geral de funcionamento da unidade', max_length=255, null=True, verbose_name='Horário de Funcionamento'),
        ),
        migrations.AddField(
            model_name='estabelecimentosaude',
            name='link',
            field=models.URLField(blank=True, help_text='Link para a página oficial da unidade', max_length=500, null=True, verbose_name='Link Oficial'),
        ),
        migrations.AddField(
            model_name='estabelecimentosaude',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone(s) de contato ou gerência', max_length=100, null=True, verbose_name='Telefone(s)'),
        ),
        migrations.AlterField(
            model_name='estabelecimentosaude',
            name='nome',
            field=models.CharField(help_text='Nome da Unidade de Saúde', max_length=255, verbose_name='Nome da Unidade'),
        ),
        migrations.AlterModelTable(
            name='estabelecimentosaude',
            table=None,
        ),
    ]
