# Generated by Django 5.2.15 on 2026-09-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstabelecimentoSaude', '0002_alter_estabelecimentosaude_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimentosaude',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Coordenada geográfica da unidade em latitude', null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='estabelecimentosaude',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Coordenada geográfica da unidade em longitude', null=True, verbose_name='Longitude'),
        ),
    ]
