# Generated by Django 5.2.15 on 2026-10-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstabelecimentoSaude', '0003_estabelecimentosaude_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimentosaude',
            name='cnes',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CNES'),
        ),
        migrations.AddField(
            model_name='estabelecimentosaude',
            name='farmaceutico',
            field=models.BooleanField(default=False, verbose_name='Possui farmacêutico'),
        ),
        migrations.AddField(
            model_name='estabelecimentosaude',
            name='horario_farmaceutico',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Horário do farmacêutico'),
        ),
    ]
