# Generated by Django 5.2.15 on 2026-07-10 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EstabelecimentoSaude', '0001_initial'),
        ('Medicamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='EstabelecimentoSaude.estabelecimentosaude')),
                ('medicamento', models.ForeignKey(db_column='medicamento_catmat', on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='Medicamento.medicamento')),
            ],
            options={
                'db_table': 'estoque',
                'constraints': [models.UniqueConstraint(fields=('medicamento', 'estabelecimento'), name='_medicamento_estabelecimento_uc')],
            },
        ),
    ]
